services:
  - type: web
    name: transfermation-api
    env: python
    plan: free
    pythonVersion: "3.10"
    buildCommand: |
      pip install --upgrade pip setuptools wheel build
      pip install --no-cache-dir -r requirements.txt
    startCommand: python -m uvicorn src.app.api.common.app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_PORT
        sync: false
